# .github/workflows/build.yml
name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Build
      run: |
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -o bin/safereader-linux-amd64 ./safereader.go
        GOOS=windows GOARCH=amd64 go build -o bin/safereader-windows-amd64.exe ./safereader.go
        GOOS=darwin GOARCH=amd64 go build -o bin/safereader-darwin-amd64 ./safereader.go
    
    # Add artifacts upload step
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: safereader-binaries
        path: |
          bin/safereader-linux-amd64
          bin/safereader-windows-amd64.exe
          bin/safereader-darwin-amd64
        retention-days: 5
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/safereader-linux-amd64
          bin/safereader-windows-amd64.exe
          bin/safereader-darwin-amd64
